#+title: Emacs Config
#+PROPERTY: header-args :tangle yes
* Initial Setup
** Lexical Bindings
#+begin_src elisp
;; -*- lexical-binding: t; -*-
#+end_src

This has to be the first line of the file.

* File System Setup
** Repository Location
First, we have to set where the Git repository is located.

If it's hosted locally, put the path to the repository here.

If it's just pulled straight from the flake, leave it as nil.
#+begin_src elisp
(setq emacs-flake-dir "~/projects/emacs-flake")
#+end_src

** Customization File
Our customisations are stored in ~\~/.emacs-customizations.el~.
To use them properly, every time Emacs launches, we check between our local customisations file and the one stored in the home file.

If the locally stored file is newer than the one in the git repository, copy the new one to git.
Otherwise, if the customizations file doesn't exist locally, copy it from git.

  #+begin_src elisp
    (let ((dir (if emacs-flake-dir emacs-flake-dir "./")))
      (if (or
           (file-newer-than-file-p (expand-file-name "emacs-customizations.el" dir)
        			       "~/.emacs-customizations.el")
           (not (file-exists-p "~/.emacs-customizations.el")))
          (copy-file (expand-file-name "emacs-customizations.el" dir) "~/.emacs-customizations.el" t)
        (when (not (file-exists-p "~/.emacs-customizations.el"))
          (copy-file "~/.emacs-customizations.el" (expand-file-name "emacs-customizations.el" dir) t))))
#+end_src

* Variables
Next, we'll set some basic variables.

** Custom File
We set the customization file to [[*File System Setup][the one that we set up earlier]]:
#+begin_src elisp
  (setq custom-file "~/.emacs-customizations.el")
#+end_src

** Basic Configs
We'll set some basic configs here - relative line numbers, silencing sound effects and some basic setup for autocomplete:
#+begin_src elisp
  (setq display-line-numbers 'relative
        ring-bell-function 'ignore

        read-file-name-completion-ignore-case t
        read-buffer-completion-ignore-case t
        completion-ignore-case t
        completion-styles '(basic substring partial-completion flex))
#+end_src

** Org Configs
Next is basic setup for org mode:
#+begin_src elisp
  (setq org-preview-latex-default-process 'dvipng
        org-roam-directory (file-truename "~/org")
        org-id-locations-file (expand-file-name ".org-id-locations" org-roam-directory)
        org-roam-db-location (expand-file-name "org-roam.db" org-roam-directory))
#+end_src

* Modes
We set all of the basic modes, of course.
#+begin_src elisp
(evil-mode 1)
(vertico-mode 1)
(ivy-mode 1)
(ivy-prescient-mode 1)
(org-roam-db-autosync-mode 1)
(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
#+end_src

* Keybinds
Now for the fun part.

** Maps
*** Window Map
This map is for moving between windows on the screen.
#+begin_src elisp
  (defvar window-map (define-keymap 
  		     "h" #'evil-window-left
  		     "j" #'evil-window-down
  		     "k" #'evil-window-up
  		     "l" #'evil-window-right
                       "H" #'window-move-left
  		     "J" #'window-move-down
  		     "K" #'window-move-up
  		     "L" #'window-move-right
  		     "v" #'+evil/window-vsplit-and-follow
  		     "n" #'+evil/window-split-and-follow
  		     "r" #'redraw-display
  		     ))
#+end_src

*** Config Map
This map is for easily accessing config files.

#+begin_src elisp
  (defvar config-map (define-keymap 
  		     "r" (lambda () (interactive) (load "~/nixos/emacs/init.el"))
  		     "h" (lambda () (interactive) (find-file "~/org/contents.org"))
  		     "c" (lambda () (interactive) (find-file "~/nixos/emacs/init.el"))
  		     "k" (lambda () (interactive) (find-file "~/nixos/emacs/modules/keybinds.el"))
  		     ))
  #+end_src

*** View Map
This map is for managing viewmodes easily.
#+begin_src elisp
  (defvar view-map (define-keymap 
  		   "v" #'org-toggle-narrow-to-subtree
  		   "h" (lambda() (interactive) (org-cycle-hide-drawers 'all))
  		   "l" #'lsp-describe-at-point
  		   ))
#+end_src

*** Buffer Map
This map is for managing and navigating buffers.
#+begin_src elisp
(defvar buffer-map (define-keymap :full t
		     "p" #'previous-buffer
		     "n" #'next-buffer
		     "b" #'buffer-menu
		     ))
#+end_src

*** Customisation Map
This map is for customising variables, faces, etc.
#+begin_src elisp
(defvar customize-map (define-keymap
		        "c" #'customize-browse
			"f" #'list-faces-display
			"v" #'customize-variable
			"g" #'customize-group
			))
#+end_src

*** Leader Map
This map is the most important one - this map appears whenever you press Space while in Evil Mode, and defines every map that you can move to.
#+begin_src elisp
(defvar leader-map (define-keymap
  "." #'find-file
  "w" window-map
  "d" config-map
  "v" view-map
  "b" buffer-map
  "c" customize-map
  "h" help-map
  "/" #'avy-goto-char-2
  ))
#+end_src

** Configuration
Set the leader map to appear whenever you press =Space= in Normal mode.
#+begin_src elisp
(evil-define-key 'normal global-map (kbd "<SPC>") leader-map)
#+end_src

=== takes you to the most recent mark.
#+begin_src elisp
(evil-define-key 'normal global-map (kbd "=") 'pop-global-mark)
#+end_src

=-= and =_= use Avy for navigating within text.
#+begin_src elisp
(evil-define-key '(list normal motion visual) global-map (kbd "-") 'avy-goto-char)
(evil-define-key '(list normal motion visual) global-map (kbd "_") 'avy-goto-line)
#+end_src

=S= is used to surround text while in Visual mode.
#+begin_src elisp
(evil-define-key 'visual global-map "S" 'surround-insert)
#+end_src

** Mode Specific Maps
*** Setup
This macro sets up a local leader keybind for a given map, mapped to =SPC M=.
All the mode-specific config being locked behind the same keybind means I actually know what my code is doing :)
#+begin_src elisp
(defmacro set-local-leader-map (current-map new-map)
  `(evil-define-key 'normal ,current-map (kbd "<SPC>")
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map leader-map)
      (define-key map (kbd "m") ,new-map)
      map
      ))
  )
#+end_src

This will turn this:
#+begin_src elisp :tangle no
(set-local-leader-map test-mode-map (define-keymap "a" #'test-function))
#+end_src
into:
#+begin_src elisp :tangle no
  (evil-define-key 'normal test-mode-map (kbd "<SPC>")
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map leader-map)
      (define-key map (kbd "m") (define-keymap
  				"a" #'test-function))
      map))
#+end_src
which makes this a LOT easier to organise.

*** Org Mode
